INSERT INTO conditions (name, weather_code) VALUES
    ('Clear', 0),
    ('Mainly Clear', 1),
    ('Partly Cloudy', 2),
    ('Overcast', 3),
    ('Fog', 45),
    ('Freezing Fog', 48),
    ('Light Drizzle', 51),
    ('Moderate Drizzle', 53),
    ('Dense Drizzle', 55),
    ('Light Freezing Drizzle', 56),
    ('Heavy Freezing Drizzle', 57),
    ('Slight Rain', 61),
    ('Moderate Rain', 63),
    ('Heavy Rain', 65),
    ('Light Freezing Rain', 66),
    ('Heavy Freezing Rain', 67),
    ('Light Snowfall', 71),
    ('Moderate Snowfall', 73),
    ('Heavy Snowfall', 75),
    ('Sleet', 77),
    ('Light Rain Showers', 80),
    ('Moderate Rain Showers', 81),
    ('Violent Rain Showers', 82),
    ('Light Snow Showers', 85),
    ('Heavy Snow Showers', 86),
    ('Thunderstorm', 95),
    ('Thunderstorm With Light Hail', 96),
    ('Thunderstorm With Heavy Hail', 99)
    ;

